POST http://localhost:5031/api/projects
Content-Type: application/json

{
  "name": "Second Mongo Project",
  "description": "Learning ASP.NET Core + MongoDB"
}

###
GET http://localhost:5031/api/projects

###
GET http://localhost:5031/api/projects/69726c13bb0fb6f852917f80

###
DELETE http://localhost:5031/api/projects/69726c13bb0fb6f852917f80

###
PUT http://localhost:5031/api/projects/697a5fd54f3fc12310bc896d
Content-Type: application/json

{
  "name": "U",
  "description": "Updated description for ASP.NET Core + MongoDB project"
}
